// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0InDO7q7ufR9TUrOascwGtxQ9xHxyx1g',
    appId: '1:1096974551566:web:b882761e2f90c4057f4a5f',
    messagingSenderId: '1096974551566',
    projectId: 'vnpay-chat-fd76d',
    authDomain: 'vnpay-chat-fd76d.firebaseapp.com',
    storageBucket: 'vnpay-chat-fd76d.firebasestorage.app',
    measurementId: 'G-SXJTQ5MDSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUptd2XUogd--_VZ3x4dPs-4LZ4jfDj3g',
    appId: '1:1096974551566:android:12e4be8336deee6d7f4a5f',
    messagingSenderId: '1096974551566',
    projectId: 'vnpay-chat-fd76d',
    storageBucket: 'vnpay-chat-fd76d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-ZQFFCrLvvCQHx2BZiSiHGrztJstt8bg',
    appId: '1:1096974551566:ios:a9d9f268f6c354737f4a5f',
    messagingSenderId: '1096974551566',
    projectId: 'vnpay-chat-fd76d',
    storageBucket: 'vnpay-chat-fd76d.firebasestorage.app',
    iosClientId: '1096974551566-2t0dqngiovtogtvm2q2kjc1547u7ik24.apps.googleusercontent.com',
    iosBundleId: 'com.vnpay.chipmunk',
  );

}